#@+leo-ver=5-thin
#@+node:gcross.20110129220506.1648: * @thin CMakeModules/FindGOTOBLAS.cmake
FIND_LIBRARY(BLAS_LIBRARIES NAMES goto2 PATH /usr/lib /usr/local/lib) 

IF (BLAS_LIBRARIES)
   SET(BLAS_FOUND TRUE)
ENDIF (BLAS_LIBRARIES)

IF (BLAS_FOUND)
   IF (NOT GOTOBLAS_FIND_QUIETLY)
      MESSAGE(STATUS "Found BLAS: ${BLAS_LIBRARIES}")
   ENDIF (NOT GOTOBLAS_FIND_QUIETLY)
ELSE (BLAS_FOUND)
   IF (GOTOBLAS_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find BLAS")
   ENDIF (GOTOBLAS_FIND_REQUIRED)
ENDIF (BLAS_FOUND)
#@-leo
