#@+leo-ver=5-thin
#@+node:gcross.20110127123226.2818: * @thin CMakeModules/FindARPACK.cmake
FIND_LIBRARY(ARPACK_LIBRARIES NAMES arpack PATH /usr/lib /usr/local/lib) 

IF (ARPACK_LIBRARIES)
   SET(ARPACK_FOUND TRUE)
ENDIF (ARPACK_LIBRARIES)

IF (ARPACK_FOUND)
   IF (NOT ARPACK_FIND_QUIETLY)
      MESSAGE(STATUS "Found ARPACK: ${ARPACK_LIBRARIES}")
   ENDIF (NOT ARPACK_FIND_QUIETLY)
ELSE (ARPACK_FOUND)
   IF (ARPACK_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find ARPACK")
   ENDIF (ARPACK_FIND_REQUIRED)
ENDIF (ARPACK_FOUND)
#@-leo
